version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: eslint-plugin-vue
    versions:
    - 7.5.0
    - 7.6.0
    - 7.7.0
  - dependency-name: husky
    versions:
    - 5.1.2
    - 5.1.3
  - dependency-name: semantic-release
    versions:
    - 17.4.1
  - dependency-name: "@commitlint/config-conventional"
    versions:
    - 12.0.1
  - dependency-name: "@vue/test-utils"
    versions:
    - 1.1.3
  - dependency-name: "@commitlint/cli"
    versions:
    - 12.0.1
  - dependency-name: js-yaml
    versions:
    - 4.0.0
  - dependency-name: sass-loader
    versions:
    - 10.1.1
